// The analyzer takes as input the match object produced by the parser and
// produces as output a contextually-checked program representation

import * as core from "./core.js"

// We want error messages from the analyzer to look like those automatically
// generated by Ohm in the parser. So we have a single point at which all
// contextual checks are made, and we throw an error with a message that
// looks like Ohm's. Pass in a condition that must be true, a message to
// report if the condition is false, and an object that contains contextual
// information about the error location. The object should have an "at"
// property whose value is a parse tree node. The error message will be
// prefixed with the line and column number of the parse tree node.
function check(condition, message, { at: errorLocation }) {
  if (!condition) {
    const prefix = errorLocation.source.getLineAndColumnMessage()
    throw new Error(`${prefix}${message}`)
  }
}

class Context {
  constructor(parent) {
    this.parent = parent
    this.locals = new Map()
  }
  add(id, entity) {
    const name = id.sourceString
    check(!this.locals.has(name), `${name} already declared`, { at: id })
    this.locals.set(name, entity)
  }
  get(name) {
    return this.locals.get(name) || this.parent?.get(name)
  }
  lookup(id, { expecting: kind }) {
    const name = id.sourceString
    const entity = this.get(name)
    check(entity, `${name} has not been declared`, { at: id })
    const hasExpectedKind = entity instanceof kind
    check(hasExpectedKind, `${name} is not a ${kind.name}`, { at: id })
    return entity
  }
}

export default function analyze(match) {
  let context = new Context()

  const analyzer = match.matcher.grammar.createSemantics().addOperation("rep", {
    Program(statements) {
      return new core.Program(statements.children.map((s) => s.rep()))
    },

    Statement_vardec(_let, id, _eq, exp, _semicolon) {
      // Analyze the initializer *before* adding the variable to the context,
      // because we don't want the variable to come into scope until after
      // the declaration. That is, "let x=x;" should be an error (unless x
      // was already defined in an outer scope.) Also we need to use the type
      // of the initializer for the type of the variable.
      const initializer = exp.rep()
      const variable = new core.Variable(id.sourceString)
      context.add(id, variable)
      return new core.VariableDeclaration(variable, initializer)
    },

    Statement_fundec(_fun, id, parameters, _equals, exp, _semicolon) {
      // Start by adding a new function object to this context. We won't
      // have its parameters yet; that will come later. But it is important
      // to get the function in the context right way, to allow recursion.
      const fun = new core.Function(id.sourceString)
      context.add(id, fun)

      // The parameters and the body will go into a new inner context. Put
      // the parameters in first, so that if there are any self-recursive
      // calls in the body, they will be able to see the parameters. After
      // the parameters and body are analyzed, pop back out to the original
      // context.
      context = new Context(context)
      fun.params = parameters.rep()
      const body = exp.rep()
      context = context.parent

      return new core.FunctionDeclaration(fun, body)
    },

    Params(_open, idList, _close) {
      return idList.asIteration().children.map((id) => {
        const entity = new core.Variable(id.sourceString)
        context.add(id, entity)
        return entity
      })
    },

    Statement_assign(id, _eq, exp, _semicolon) {
      return new core.Assignment(id.rep(), exp.rep())
    },

    Statement_print(_print, exp, _semicolon) {
      return new core.PrintStatement(exp.rep())
    },

    Statement_while(_while, exp, block) {
      return new core.WhileStatement(exp.rep(), block.rep())
    },

    Block(_open, statements, _close) {
      return statements.children.map((s) => s.rep())
    },

    Exp_unary(op, exp) {
      return new core.UnaryExpression(op.sourceString, exp.rep())
    },

    Exp_ternary(exp1, _questionMark, exp2, _colon, exp3) {
      return new core.Conditional(exp1.rep(), exp2.rep(), exp3.rep())
    },

    Exp1_binary(exp1, op, exp2) {
      return new core.BinaryExpression(op.sourceString, exp1.rep(), exp2.rep())
    },

    Exp2_binary(exp1, op, exp2) {
      return new core.BinaryExpression(op.sourceString, exp1.rep(), exp2.rep())
    },

    Exp3_binary(exp1, op, exp2) {
      return new core.BinaryExpression(op.sourceString, exp1.rep(), exp2.rep())
    },

    Exp4_binary(exp1, op, exp2) {
      return new core.BinaryExpression(op.sourceString, exp1.rep(), exp2.rep())
    },

    Exp5_binary(exp1, op, exp2) {
      return new core.BinaryExpression(op.sourceString, exp1.rep(), exp2.rep())
    },

    Exp6_binary(exp1, op, exp2) {
      return new core.BinaryExpression(op.sourceString, exp1.rep(), exp2.rep())
    },

    Exp7_parens(_open, exp, _close) {
      return exp.rep()
    },

    Call(id, open, expList, _close) {
      const callee = context.lookup(id, { expecting: core.Function })
      const args = expList.asIteration().children.map((exp) => exp.rep())
      const [paramCount, argCount] = [callee.params.length, args.length]
      const message = `${paramCount} argument(s) required but ${argCount} passed`
      check(argCount === paramCount, message, { at: open })
      return new core.Call(callee, args)
    },

    Exp7_id(id) {
      return context.lookup(id, { expecting: core.Variable })
    },

    true(_) {
      return 1
    },

    false(_) {
      return 0
    },

    numeral(_whole, _point, _fraction) {
      return Number(this.sourceString)
    },
  })

  return analyzer(match).rep()
}
